Ejercicios Parcial 3 - Métodos Computacionales 1

Catalina Fuentes y Silvana Archila

Algebra lineal

Ejercico #4: Algoritmo multiplicación de matrices

In [12]:
import numpy as np 
import sympy as sym

In [15]:
#Creando algoritmo que multiplica matrices
def multiplicar_matrices(matrizA, matrizB):

    #Alerta si las matrices no se pueden multiplicar 
    if matrizA.shape[1] != matrizB.shape[0]:
        x = str("Las dimensiones de las matrices no permiten la multiplicación.")
        compatibles = 0
        return x

    compatibles = 1
    
    #Creando matriz de ceros con las dimensiones adecuadas
    filas_multip = matrizA.shape[0]
    colum_multip = matrizB.shape[1]
    multiplicacion = np.zeros((filas_multip, colum_multip))

    #Realizando la multiplicación de las matrices
    if compatibles != 0:
        for i in range(filas_multip):
            for j in range(colum_multip):
                for k in range(matrizB.shape[0]):
                    multiplicacion[i][j] += matrizA[i][k] * matrizB[k][j]

        return multiplicacion

In [16]:
#Usar el algoritmo para calcular la multiplicación de las 2 matrices dadas

matrizA = np.array([[1,0,0], [5,1,0], [-2,3,1]])
matrizB = np.array([[4,-2,1], [0,3,7], [0,0,2]])

multiplicacion = multiplicar_matrices(matrizA,matrizB)

print("La multiplicación de las 2 matrices dadas tiene como resultado:" )
print(multiplicacion)

La multiplicación de las 2 matrices dadas tiene como resultado:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
