In [23]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

Parcial #3

Catalina Fuentes y Silvana Archila


In [24]:
#Genero 2 simbolos reales para X y Y
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)


#Defino un símbolo complejo Z
z = x + (sym.I)*y

#Defino constante C
W = 114.6
q = 3*10**(-4)
L = 5
k = 9*10**(9)

C = ((k**2 * q**4)/(L**4 * W**2))*((np.sqrt(2)/2)+(1/4))**2
C

0.07322199739508203

Hallando raices complejas

In [25]:
#Calculo función compleja
funcion = (z)**6 + C*(z)**2 - C
funcion

(x + I*y)**6 + 0.073221997395082*(x + I*y)**2 - 0.073221997395082

In [26]:
#Guardo la parte real e imaginaria de la función en una lista
F = [sym.re(funcion),sym.im(funcion)]
F

[x**6 - 15*x**4*y**2 + 15*x**2*y**4 + 0.073221997395082*x**2 - y**6 - 0.073221997395082*y**2 - 0.073221997395082,
 6*x**5*y - 20*x**3*y**3 + 6*x*y**5 + 0.146443994790164*x*y]

In [27]:
#Hallo el Jacobiano de F
def GetJacobian(funcion, variables):
    #Miro cantidad de funciones y variables para saber las dimensiones de la Jacobiana
    num_funciones = len(funcion)
    num_variables = len(variables)
    
    #Creo matriz de ceros de las dimensiones halladas antes
    Jacobiana = sym.Matrix.zeros(num_funciones, num_variables)
    
    #Hago la jacobiana
    for i in range(num_funciones):
        for j in range(num_variables):
            Jacobiana[i, j] = sym.diff(funcion[i], variables[j])
    
    return Jacobiana

funciones = [F[0], F[1]]
variables = [x, y]

J = GetJacobian(funciones, variables)
J

Matrix([
[6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x, -30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y],
[30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y,  6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x]])

In [28]:
#Hallo inverso del jacobiano
InvJ = J.inv(method='LU')
InvJ

Matrix([
[(1 + (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/((6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)*(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x - (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x))))/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x), -(-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)/((6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)*(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x - (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)))],
[                                                                                                                          -(30*x**4*y - 60*x**2*y**3 + 6*y*

In [29]:
#Convierto función a Numpy
Fn = sym.lambdify([x,y],F,'numpy')

#Convierto Jacobiano a Numpy
Jn = sym.lambdify([x,y],J,'numpy')

#Convierto el inverso del Jacobiano a Numpy
IJn = sym.lambdify([x,y],InvJ,'numpy')

In [30]:
#Realizo método de Newton Raphson
def NewtonRaphson(z,Fn,Jn,itmax=100,precision=1e-9):
    
    error = 1
    it = 0
    
    while error > precision and it < itmax:
        
        IFn = Fn(z[0],z[1])
        IJn = Jn(z[0],z[1])
        
        z1 = z - np.dot(IJn,IFn)
        
        error = np.max( np.abs(z1-z) )
        
        z = z1
        it +=1
        
    return z

In [41]:
#Hallo raices
z0 = np.array([-1,0])
sol1 = NewtonRaphson(z0,Fn,IJn)

z1 = np.array([1,0])
sol2 = NewtonRaphson(z1,Fn,IJn)

z2 = np.array([1,-2])
sol3 = NewtonRaphson(z2,Fn,IJn)

z3 = np.array([-1,2])
sol4 = NewtonRaphson(z3,Fn,IJn)

z4 = np.array([1,2])
sol5 = NewtonRaphson(z4,Fn,IJn)

z5 = np.array([-1,-2])
sol6 = NewtonRaphson(z5,Fn,IJn)

Reales = [sol1,sol2]
print("Raices reales:")
Reales


Raices reales:


[array([-0.60037119,  0.        ]), array([0.60037119, 0.        ])]

In [42]:
Complejas = [sol3,sol4,sol5,sol6]
print("Raices complejas:")
Complejas 

Raices complejas:


[array([ 0.36775746, -0.56166568]),
 array([-0.36775746,  0.56166568]),
 array([0.36775746, 0.56166568]),
 array([-0.36775746, -0.56166568])]

In [43]:
#Hallando el ángulo
angulo1 = np.arcsin(sol1[0])
angulo2 = np.arcsin(sol2[0])

#Pasándolos a grados
angulo1 = angulo1*180/np.pi
angulo2 = angulo2*180/np.pi

angulo1, angulo2


(-36.89648713980008, 36.89648713980008)

Hallo raices en el intervalo 0 a 2pi

In [31]:
"""intx = np.linspace(0, 2*np.pi, 10)
inty = np.linspace(0, 2*np.pi, 8)

# Realizar la búsqueda de raíces automáticamente en la región de muestreo
roots = []
roots_reals = []
for i in intx:
    for j in inty:
        z0 = np.array([i, j])
        zsol = NewtonRaphson(z0, Fn, IJn)
        zsol =  np.round(zsol,5)
        roots.append(zsol)
        
# Usamos np.unique para eliminar raíces duplicadas
unique_roots_array = np.unique(roots, axis=0)
unique_roots_array
"""

'intx = np.linspace(0, 2*np.pi, 10)\ninty = np.linspace(0, 2*np.pi, 8)\n\n# Realizar la búsqueda de raíces automáticamente en la región de muestreo\nroots = []\nroots_reals = []\nfor i in intx:\n    for j in inty:\n        z0 = np.array([i, j])\n        zsol = NewtonRaphson(z0, Fn, IJn)\n        zsol =  np.round(zsol,5)\n        roots.append(zsol)\n        \n# Usamos np.unique para eliminar raíces duplicadas\nunique_roots_array = np.unique(roots, axis=0)\nunique_roots_array\n'

In [32]:
"""
#Raices complejas 
z0 = np.array([1,-2])
sol1 = NewtonRaphson(z0,Fn,IJn)

z1 = np.array([1,2])
sol2 = NewtonRaphson(z1,Fn,IJn)

z2 = np.array([3,2])
sol3 = NewtonRaphson(z2,Fn,IJn)

z3 = np.array([3,-2])
sol4 = NewtonRaphson(z3,Fn,IJn)

Complejas = [sol1,sol2,sol3,sol4]
print("Raices complejas:")
Complejas
"""

'\n#Raices complejas \nz0 = np.array([1,-2])\nsol1 = NewtonRaphson(z0,Fn,IJn)\n\nz1 = np.array([1,2])\nsol2 = NewtonRaphson(z1,Fn,IJn)\n\nz2 = np.array([3,2])\nsol3 = NewtonRaphson(z2,Fn,IJn)\n\nz3 = np.array([3,-2])\nsol4 = NewtonRaphson(z3,Fn,IJn)\n\nComplejas = [sol1,sol2,sol3,sol4]\nprint("Raices complejas:")\nComplejas\n'

In [33]:
#Raices reales (componente imaginaria igual a 0, por lo que son raices reales)
"""
z4 = np.array([2.,-2.])
sol5 = NewtonRaphson(z4,Fn,IJn)
sol5[1] = round(sol5[1],9)

z5 = np.array([1.,1.])
sol6 = NewtonRaphson(z5,Fn,IJn)
sol6[1] = round(sol6[1],9)

Reales = [sol5,sol6]
print("Raices reales:")
Reales
"""

'\nz4 = np.array([2.,-2.])\nsol5 = NewtonRaphson(z4,Fn,IJn)\nsol5[1] = round(sol5[1],9)\n\nz5 = np.array([1.,1.])\nsol6 = NewtonRaphson(z5,Fn,IJn)\nsol6[1] = round(sol6[1],9)\n\nReales = [sol5,sol6]\nprint("Raices reales:")\nReales\n'