In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

Parcial #3

Catalina Fuentes y Silvana Archila

PROBLEMA 22

A. (Teórico)

B. Hallar las 6 raices de la ecuación

In [4]:
#Genero 2 simbolos reales para X y Y
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)


#Defino un símbolo complejo Z
z = x + (sym.I)*y

#Defino constante C
W = 114.6
q = 3*10**(-4)
L = 5
k = 9*10**(9)

C = ((k**2 * q**4)/(L**4 * W**2))*((np.sqrt(2)/2)+(1/4))**2
C

0.07322199739508203

In [5]:
#Calculo función compleja
funcion = (z)**6 + C*(z)**2 - C
funcion

(x + I*y)**6 + 0.073221997395082*(x + I*y)**2 - 0.073221997395082

In [6]:
#Guardo la parte real e imaginaria de la función en una lista
F = [sym.re(funcion),sym.im(funcion)]
F

[x**6 - 15*x**4*y**2 + 15*x**2*y**4 + 0.073221997395082*x**2 - y**6 - 0.073221997395082*y**2 - 0.073221997395082,
 6*x**5*y - 20*x**3*y**3 + 6*x*y**5 + 0.146443994790164*x*y]

In [7]:
#Hallo el Jacobiano de F
def GetJacobian(funcion, variables):
    #Miro cantidad de funciones y variables para saber las dimensiones de la Jacobiana
    num_funciones = len(funcion)
    num_variables = len(variables)
    
    #Creo matriz de ceros de las dimensiones halladas antes
    Jacobiana = sym.Matrix.zeros(num_funciones, num_variables)
    
    #Hago la jacobiana
    for i in range(num_funciones):
        for j in range(num_variables):
            Jacobiana[i, j] = sym.diff(funcion[i], variables[j])
    
    return Jacobiana

funciones = [F[0], F[1]]
variables = [x, y]

J = GetJacobian(funciones, variables)
J

Matrix([
[6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x, -30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y],
[30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y,  6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x]])

In [8]:
#Hallo inverso del jacobiano
InvJ = J.inv(method='LU')
InvJ

Matrix([
[(1 + (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/((6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)*(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x - (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x))))/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x), -(-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)/((6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)*(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x - (-30*x**4*y + 60*x**2*y**3 - 6*y**5 - 0.146443994790164*y)*(30*x**4*y - 60*x**2*y**3 + 6*y**5 + 0.146443994790164*y)/(6*x**5 - 60*x**3*y**2 + 30*x*y**4 + 0.146443994790164*x)))],
[                                                                                                                          -(30*x**4*y - 60*x**2*y**3 + 6*y*

In [9]:
#Convierto función a Numpy
Fn = sym.lambdify([x,y],F,'numpy')

#Convierto Jacobiano a Numpy
Jn = sym.lambdify([x,y],J,'numpy')

#Convierto el inverso del Jacobiano a Numpy
IJn = sym.lambdify([x,y],InvJ,'numpy')

In [10]:
#Realizo método de Newton Raphson
def NewtonRaphson(z,Fn,Jn,itmax=100,precision=1e-9):
    
    error = 1
    it = 0
    
    while error > precision and it < itmax:
        
        IFn = Fn(z[0],z[1])
        IJn = Jn(z[0],z[1])
        
        z1 = z - np.dot(IJn,IFn)
        
        error = np.max( np.abs(z1-z) )
        
        z = z1
        it +=1
        
    return z

In [11]:
#Hallo raices
z0 = np.array([-1,0])
sol1 = NewtonRaphson(z0,Fn,IJn)

z1 = np.array([1,0])
sol2 = NewtonRaphson(z1,Fn,IJn)

z2 = np.array([1,-2])
sol3 = NewtonRaphson(z2,Fn,IJn)

z3 = np.array([-1,2])
sol4 = NewtonRaphson(z3,Fn,IJn)

z4 = np.array([1,2])
sol5 = NewtonRaphson(z4,Fn,IJn)

z5 = np.array([-1,-2])
sol6 = NewtonRaphson(z5,Fn,IJn)

Reales = [sol1,sol2]
print("Raices reales:")
Reales


Raices reales:


[array([-0.60037119,  0.        ]), array([0.60037119, 0.        ])]

In [12]:
Complejas = [sol3,sol4,sol5,sol6]
print("Raices complejas:")
Complejas 

Raices complejas:


[array([ 0.36775746, -0.56166568]),
 array([-0.36775746,  0.56166568]),
 array([0.36775746, 0.56166568]),
 array([-0.36775746, -0.56166568])]

C. Ángulo de equilibrio

In [13]:
#Elijo raices reales
angulo1 = np.arcsin(sol1[0])
angulo2 = np.arcsin(sol2[0])

#Pasándolos a grados
angulo1 = angulo1*180/np.pi
angulo2 = angulo2*180/np.pi

angulo1, angulo2

(-36.89648713980008, 36.89648713980008)

In [14]:
#El ángulo de equilibrio es el positivo
angulo_equil = angulo2
angulo_equil

36.89648713980008